[package]
name = "hyperlane"
version = "2.19.0"
edition = "2021"
authors = ["ltpp-universe <root@ltpp.vip>"] 
license = "MIT"
description = """Hyperlane is a lightweight and high-performance Rust HTTP server library designed to simplify network service development. It supports HTTP request parsing, response building, TCP communication, and redirection features, making it ideal for building modern web services."""
keywords = ["http", "request", "response", "tcp", "redirect"]
repository = "https://github.com/ltpp-universe/hyperlane.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",
    "Cargo.lock",
    "sh",
    ".github"
]

[dependencies]
color-output = "6.1.4"
http-request = "8.17.0"
http-type = "2.7.0"
hyperlane-log = "0.8.0"
hyperlane-time = "0.0.1"
lombok-macros = "1.5.0"
std-macro-extensions = "0.17.6"

[profile.dev]
incremental = true
opt-level = 3
lto = true
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
