[package]
name = "hyperlane"
version = "4.42.0"
edition = "2024"
authors = ["ltpp-universe <root@ltpp.vip>"] 
license = "MIT"
description = """Hyperlane is a lightweight and high-performance Rust HTTP server library designed to simplify network service development. It supports HTTP request parsing, response building, and TCP communication, making it ideal for building modern web services. Additionally, it provides support for request and response middleware, WebSocket, and Server-Sent Events (SSE), enabling flexible and efficient real-time communication."""
keywords = ["http", "request", "response", "tcp", "redirect"]
repository = "https://github.com/ltpp-universe/hyperlane.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",
    "Cargo.lock",
    "sh",
    ".github",
    "logs",
    "**/*.log"
]

[dependencies]
async-func = "0.2.0"
clonelicious = "1.1.0"
color-output = "6.5.0"
file-operation = "0.5.0"
http-compress = "2.4.0"
hyperlane-log = "1.3.0"
lombok-macros = "1.9.0"
recoverable-spawn = "3.5.0"
recoverable-thread-pool = "2.1.0"
std-macro-extensions = "0.22.0"
tokio = { version = "1.44.1", features = ["full"] }
once_cell = "1.21.1"
simd-json = "0.15.0"
serde = "1.0.219"
serde_json = "1.0.140"
http-type = "3.31.0"
futures = "0.3.31"
server-manager = "3.1.0"
hyperlane-time = "0.2.0"

[profile.dev]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"

[profile.release]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"
