[package]
name = "hyperlane"
version = "3.10.0"
edition = "2021"
authors = ["ltpp-universe <root@ltpp.vip>"] 
license = "MIT"
description = """Hyperlane is a lightweight and high-performance Rust HTTP server library designed to simplify network service development. It supports HTTP request parsing, response building, TCP communication, and redirection features, making it ideal for building modern web services."""
keywords = ["http", "request", "response", "tcp", "redirect"]
repository = "https://github.com/ltpp-universe/hyperlane.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",
    "Cargo.lock",
    "sh",
    ".github"
]

[dependencies]
async-func = "0.1.0"
clonelicious = "1.0.0"
color-output = "6.1.4"
file-operation = "0.4.0"
http-compress = "2.2.2"
http-request = "8.37.6"
hyperlane-log = "1.1.19"
hyperlane-time = "0.0.5"
lombok-macros = "1.7.0"
recoverable-spawn = "3.3.3"
recoverable-thread-pool = "2.0.4"
std-macro-extensions = "0.21.0"
tokio = { version = "1.43.0", features = ["full"] }
once_cell = "1.20.3"
simd-json = "0.14.3"
serde = "1.0.217"
serde_json = "1.0.138"

[profile.dev]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"
backtrace = "off"

[profile.release]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"
backtrace = "off"
