name: Rust

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Make test.sh executable
        run: chmod +x ./sh/test.sh
      - name: Run tests
        run: ./sh/test.sh
