name: Rust

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read_version.outputs.version }}
      tag: ${{ steps.read_version.outputs.tag }}
    steps:
      - name: checkout_code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install_rust_toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: cache_cargo_registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: install_toml_cli
        run: cargo install toml-cli

      - name: cache_toml_cli
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/toml
          key: toml-cli-${{ runner.os }}

      - name: read_version_from_cargo_toml
        id: read_version
        run: |
          VERSION=$(toml get Cargo.toml package.version --raw)
          echo "detected version: $VERSION"
          if [ -z "$VERSION" ]; then
            echo "❌ failed to read version from Cargo.toml"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

  check_format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: install_rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt

      - name: run_cargo_fmt
        run: cargo fmt -- --check

  run_tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: install_rust_toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: run_cargo_tests
        run: cargo test --all-features -- --nocapture

  run_clippy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: install_clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - name: run_cargo_clippy
        run: cargo clippy --all-features -- -A warnings

  build_release:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: install_rust_toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: run_cargo_check
        run: cargo check --release --all-features

  publish_crate:
    needs: [setup, check_format, run_tests, run_clippy, build_release]
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.try_publish.outputs.published }}
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: try_to_publish_crate
        id: try_publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          set -e
          echo "published=false" >> $GITHUB_OUTPUT
          echo "${{ secrets.CARGO_REGISTRY_TOKEN }}" | cargo login
          if cargo publish --allow-dirty; then
            echo "published=true" >> $GITHUB_OUTPUT
          else
            echo "❌ publish failed, but continuing."
          fi

  create_release:
    needs: [setup, publish_crate]
    permissions:
      contents: write
      packages: write
    if: needs.publish_crate.outputs.published == 'true' && needs.setup.outputs.tag != ''
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create_github_release
        run: |
          gh release create "${{ needs.setup.outputs.tag }}" \
            --title "${{ needs.setup.outputs.tag }}" \
            --notes "Release ${{ needs.setup.outputs.tag }}" \
            --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  success_notice:
    needs: [setup, publish_crate, create_release]
    if: needs.publish_crate.outputs.published == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: restore_toml_cli
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/toml
          key: toml-cli-${{ runner.os }}

      - name: output_release_info
        run: |
          PACKAGE_NAME=$(toml get Cargo.toml package.name --raw)
          echo "✅ released version ${{ needs.setup.outputs.version }}"
          echo "📦 https://crates.io/crates/$PACKAGE_NAME"
          echo "🏷️  tag: ${{ needs.setup.outputs.tag }}"
          echo "🚀 release: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ needs.setup.outputs.tag }}"
